### ISSUE TITLE
Update PPO for better performance and closer alignment to sb3

### ISSUE THREAD

**Issue by paradite** [StoneT2000/rl-ts#38]
Recently I played with the PPO model in `rl-ts` and found that the model was not very stable when playing the cartpole environment.

So I made a few changes and bug fixes with reference to the [PPO implementation](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py) in sb3:

- Add mini-batch updates
- Unified policy and value function optimizers into one and combined loss from policy and value function
- Adjusted return formula according to sb3 [updated implementation](https://github.com/DLR-RM/stable-baselines3/pull/375)
- Updated a few formulas to match sb3 more closely
- Removed KL limit by default

These changes made the implementation (magenta) much more stable and reach optimal return earlier as compared to the original one(blue and black):

<img width="393" alt="Screenshot 2023-03-16 at 5 40 08 PM" src="https://user-images.githubusercontent.com/1209810/225577190-3b37d401-9b11-4edc-a3a0-b488654c7610.png">

I checked the sb3 version and it also doesn't have max KL limit by default, though it does reach the max limit of `1.5 * 0.01` slower (epoch 7/8) than this implementation (1/2). So more work is needed to get closer match to sb3.

Let me know if you are interested in updating this library. I can open a PR to merge my updates.

**Comment by paradite** [comment]
<img width="1044" alt="Screenshot 2023-03-17 at 7 21 08 PM" src="https://user-images.githubusercontent.com/1209810/225895301-77744e96-128b-41fa-94d2-d512fdf5fe5a.png">

Made more bug fixes and improvements and vf_loss is now similar to sb3 version. The only issue left is that the KL is still reaching max limit more frequently and earlier than the sb3 version.

**Comment by StoneT2000** [comment]
i'll welcome a PR! 

In fact this library needs some massive changing as it was built to reference spinning ups implementations but they don't scale well on GPU due to storing the model on each separate cpu thread and combining gradients

**Comment by paradite** [comment]
Ok I will open a PR to merge meaningful changes. 

Another thing in parallel computation: it seems that tfjs doesn't allow tidy in async functions, so there are memory leaks in the current implementation. 

I had to remove the cluster tools in my code to resolve the memory leak, but I won't include that in this PR as it is a big change. Have to investigate how to get the parallel setup working without async or somehow clean up the tensors in another way.
